@baseUrl = http://localhost:3000

###

# @name Recados

GET {{baseUrl}}/recados/
#?limit=10
#&offset=10

###

# @name LocalizarUmRecado

GET {{baseUrl}}/recados/3

###

# @name CriarUmNovoRecado

POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo recado",
    "de": "João",
    "para": "José"
}

###

# @name AtualizaUmRecado

PATCH {{baseUrl}}/recados/4
Content-Type: application/json

{
    "texto": "atualizar Recado",
    "de": "João",
    "para": "José",
    "lido": true
}

###

# @name DeletandoUmRecado

DELETE  {{baseUrl}}/recados/3/


