@baseUrl = http://localhost:3000

###

# @name Recados

GET {{baseUrl}}/recados/
#?limit=10
#&offset=10

###

# @name LocalizarUmRecado

GET {{baseUrl}}/recados/3

###

# @name CriarUmNovoRecado

POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo recado",
    "de": "João",
    "para": "José"
}

###

# @name AtualizaUmRecado

PATCH {{baseUrl}}/recados/4
Content-Type: application/json

{
    "texto": "atualizar Recado",
    "de": "João",
    "para": "José",
    "lido": true
}

###

# @name DeletandoUmRecado

DELETE  {{baseUrl}}/recados/3/


###


# @name Pessoas

GET {{baseUrl}}/pessoas/
#?limit=10
#&offset=10

###

# @name LocalizarUmaPessoas

GET {{baseUrl}}/pessoas/17

###

# @name CriarUmNovoRecado

POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "jonas@gmail.com",
    "password": "12345",
    "name": "jonas"
}

###

# @name AtualizaUmRecado

PATCH {{baseUrl}}/pessoas/6/
Content-Type: application/json

{
    "password": "teste"
}

###

# @name DeletandoUmaPessoa

DELETE  {{baseUrl}}/pessoas/15/

